FROM registry.access.redhat.com/jboss-eap-6/eap64-openshift:latest

#### Add the JDBC Driver into the module directory
COPY postgresql-9.4.1212.jre6.jar ${JBOSS_HOME}/modules/system/layers/openshift/org/postgresql/main
#### Replace the definition of current driver for a new one
RUN  sed -i -e 's/postgresql-jdbc.jar/postgresql-9.4.1212.jre6.jar/' ${JBOSS_HOME}/modules/system/layers/openshift/org/postgresql/main/module.xml && \
#### Add a Driver for PostGresql
#     sed -i '/                <drivers>/a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ <driver name=\"postgresql\" module=\"org.postgresql\">\n                        <driver-class>org.postgresql.Driver</driver-class>\n                        <xa-datasource-class>org.postgresql.xa.PGXADataSource</xa-datasource-class>\n                    </driver>' ${JBOSS_HOME}/standalone/configuration/standalone-openshift.xml && \
#### Add a new DataSource with the following variables: BACKEND_DS_CONNECTION, BACKEND_DS_USERNAME, BACKEND_DS_PASSWORD
     sed -i '/            <datasources>/a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ <datasource jta=\"true\" jndi-name=\"java:jboss/datasources/bodbaVE\" pool-name=\"java:jboss/datasources/bodbaVE\" enabled=\"true\" use-ccm=\"true\" statistics-enabled=\"false\">\n                    <connection-url>${env.BACKEND_DS_CONNECTION}</connection-url>\n                    <driver-class>org.postgresql.Driver</driver-class>\n                    <driver>postgresql</driver>\n                    <security>\n                        <user-name>${env.BACKEND_DS_USERNAME}</user-name>\n                        <password>${env.BACKEND_DS_PASSWORD}</password>\n                    </security>\n                    <validation>\n                        <validate-on-match>false</validate-on-match>\n                        <background-validation>false</background-validation>\n                    </validation>\n                    <timeout>\n                        <set-tx-query-timeout>false</set-tx-query-timeout>\n                        <blocking-timeout-millis>0</blocking-timeout-millis>\n                        <idle-timeout-minutes>0</idle-timeout-minutes>\n                        <query-timeout>0</query-timeout>\n                        <use-try-lock>0</use-try-lock>\n                        <allocation-retry>0</allocation-retry>\n                        <allocation-retry-wait-millis>0</allocation-retry-wait-millis>\n                    </timeout>\n                    <statement>\n                        <share-prepared-statements>false</share-prepared-statements>\n                    </statement>\n                </datasource>' ${JBOSS_HOME}/standalone/configuration/standalone-openshift.xml && \
#### Add a new DataSource with the following variables: FRONTEND_DS_CONNECTION, FRONTEND_DS_USERNAME, FRONTEND_DS_PASSWORD     
     sed -i '/            <datasources>/a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ <datasource jta=\"true\" jndi-name=\"java:jboss/datasources/fodbaVE\" pool-name=\"postgres\" enabled=\"true\" use-ccm=\"true\" statistics-enabled=\"false\">\n                    <connection-url>${env.FRONTEND_DS_CONNECTION}</connection-url>\n                    <driver-class>org.postgresql.Driver</driver-class>\n                    <driver>postgresql</driver>\n                    <security>\n                        <user-name>${env.FRONTEND_DS_USERNAME}</user-name>\n                        <password>${env.FRONTEND_DS_PASSWORD}</password>\n                    </security>\n                    <validation>\n                        <validate-on-match>false</validate-on-match>\n                        <background-validation>false</background-validation>\n                    </validation>\n                    <timeout>\n                        <set-tx-query-timeout>false</set-tx-query-timeout>\n                        <blocking-timeout-millis>0</blocking-timeout-millis>\n                        <idle-timeout-minutes>0</idle-timeout-minutes>\n                        <query-timeout>0</query-timeout>\n                        <use-try-lock>0</use-try-lock>\n                        <allocation-retry>0</allocation-retry>\n                        <allocation-retry-wait-millis>0</allocation-retry-wait-millis>\n                    </timeout>\n                    <statement>\n                        <share-prepared-statements>false</share-prepared-statements>\n                    </statement>\n                </datasource>' ${JBOSS_HOME}/standalone/configuration/standalone-openshift.xml
